import './modules/animation.js';
import './modules/stickyHeader.js';
import './modules/mailCopy.js';
import './modules/userPanel.js';
import './modules/languageSelect.js';
import './modules/navigationMenu.js';
import './modules/installLink.js';
import './modules/chatgpt.js';
import './modules/tolgee.js';
